#! /bin/sh

sxhkd &
xrandr --output LVDS-1 --off &
xrandr -r 75 &
xcompmgr &
polybar example &
hsetroot -cover /home/guilberc/Imagens/backgrounds/vector_wallpaper_3440x1440_by_friekdesign-dactfp5.png &
xsetroot -cursor_name left_ptr &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         4
bspc config window_gap          5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Sxiv state=floating center=true
bspc rule -a Lxterminal state=floating